# DataSource Config
spring:
#  web:
#    resources:
#      add-mappings: false
#  mvc:
#    favicon:
#      enabled: false
  # redis 配置
  data:
    redis:
      database: 0
      # 地址
      host: 127.0.0.1
      # 端口，默认为6379
      port: 6379
      # 密码
      password: 123456
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
  datasource:
    driver-class-name: org.h2.Driver
    password: sa
    url: jdbc:h2:file:./demo-db;NON_KEYWORDS=user
    username: sa
    druid:
      aop-patterns: com.alibaba.druid.spring.boot.demo.service.*
      async-close-connection-enable: true
      filter:
        stat:
          db-type: h2
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
      initial-size: 2
      max-active: 30
      max-pool-prepared-statement-per-connection-size: 5
      max-wait: 1234
      min-evictable-idle-time-millis: 30001
      min-idle: 2
      pool-prepared-statements: true
      stat-view-servlet:
        enabled: true
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 10000
      validation-query: select 1
      validation-query-timeout: 1
      web-stat-filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  main:
    allow-bean-definition-overriding: true
#  sql:
#    init:
#      schema-locations: classpath:db/schema-h2.sql
#      data-locations: classpath:db/data-h2.sql
#      mode: always

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug

#mybatis-plus:
#  type-aliases-package: com.example2.demo4.entity
#  mapper-locations: classpath:/mapper/*Mapper.xml


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30


# 忽略url
ignored:
  noLoginVerification:
    - /druid/**
    - /oauth/*
    - /captchaImage
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /v2/api-docs
    - /**.js
    - /**.css
    - /**.png
    - /**.ico
    - /webjars/**
    - /swagger-resources/**
    - /csrf
    - /anonymous/**
  urls:
    - /admin/login
    - /anonymous/**
